<?php
$nomes = array(
    "Miguel",
    "Davi",
    "Arthur",
    "Gabriel",
    "Pedro",
    "Lucas",
    "Matheus",
    "Bernardo",
    "Rafael",
    "Guilherme",
    "Enzo",
    "Felipe",
    "Gustavo",
    "Nicolas",
    "Heitor",
    "Samuel",
    "Joao Pedro",
    "Pedro Henrique",
    "Caua",
    "Henrique",
    "Murilo",
    "Eduardo",
    "Vitor",
    "Daniel",
    "Lorenzo",
    "Vinicius",
    "Pietro",
    "Joao Vitor",
    "Leonardo",
    "Theo",
    "Caio",
    "Isaac",
    "Lucca",
    "Joao",
    "Davi Lucas",
    "Enzo Gabriel",
    "Yuri",
    "Bryan",
    "Thiago",
    "Joao Gabriel",
    "Benjamin",
    "Joaquim",
    "Emanuel",
    "Thomas",
    "Ryan",
    "Carlos Eduardo",
    "Rodrigo",
    "Ian",
    "Fernando",
    "Bruno",
    "Otavio",
    "Francisco",
    "Calebe",
    "Igor",
    "Antonio",
    "Erick",
    "Joao Lucas",
    "Luiz Felipe",
    "Andre",
    "Davi Lucca",
    "Kaique",
    "Nathan",
    "Luiz Miguel",
    "Breno",
    "Vitor Hugo",
    "João Guilherme",
    "Benicio",
    "Augusto",
    "Joao Miguel",
    "Pedro Lucas",
    "Levi",
    "Anthony",
    "Yago",
    "Danilo",
    "Juan",
    "Kaue",
    "Diego",
    "Vicente",
    "Davi Luiz",
    "Luiz Gustavo",
    "Alexandre",
    "Raul",
    "Luan",
    "Diogo",
    "Marcelo",
    "Ricardo",
    "Luiz Henrique",
    "Henry",
    "Noah",
    "Enrico",
    "Lucas Gabriel",
    "Renan",
    "Luiz Otavio",
    "Pedro Miguel",
    "William",
    "Icaro",
    "Giovanni",
    "Joao Paulo",
    "Paulo",
    "Adryan",
    "Sophia",
    "Julia",
    "Alice",
    "Manuela",
    "Isabella",
    "Laura",
    "Maria Eduarda",
    "Giovanna",
    "Valentina",
    "Beatriz",
    "Luiza",
    "Helena",
    "Maria Luiza",
    "Isadora",
    "Mariana",
    "Gabriela",
    "Ana Clara",
    "Rafaela",
    "Maria Clara",
    "Isabelly",
    "Yasmin",
    "Ana Julia",
    "Livia",
    "Lara",
    "Lorena",
    "Heloisa",
    "Melissa",
    "Sarah",
    "Ana Luiza",
    "Leticia",
    "Nicole",
    "Ana Beatriz",
    "Emanuelly",
    "Esther",
    "Lavinia",
    "Marina",
    "Cecilia",
    "Rebeca",
    "Vitoria",
    "Maria Fernanda",
    "Larissa",
    "Clara",
    "Carolina",
    "Bianca",
    "Alicia",
    "Fernanda",
    "Gabrielly",
    "Catarina",
    "Ana Laura",
    "Emilly",
    "Eduarda",
    "Amanda",
    "Pietra",
    "Agatha",
    "Milena",
    "Maria Alice",
    "Lais",
    "Maria Julia",
    "Maria",
    "Elisa",
    "Stella",
    "Maria Vitoria",
    "Bruna",
    "Ana Sophia",
    "Bárbara",
    "Maria Cecilia",
    "Olivia",
    "Nathalia",
    "Camila",
    "Ana Carolina",
    "Maite",
    "Eloa",
    "Luana",
    "Luna",
    "Ana Livia",
    "Brenda",
    "Alana",
    "Sophie",
    "Ana",
    "Isabel",
    "Mirella",
    "Juliana",
    "Marcela",
    "Isis",
    "Iara",
    "Antonia",
    "Kamilly",
    "Alexia",
    "Lis",
    "Maria Sophia",
    "Joana",
    "Clarice",
    "Ayla",
    "Caroline",
    "Antonella",
    "Evellyn",
    "Malu",
    "Maria Laura",
    "Mikaela",
    "Stefany"
);
$resultado = array();
foreach($nomes as $valor) {
    if(strpos($valor,$_REQUEST["nome"]) !== false) {
        $resultado[] = $valor;
    }
}
echo json_encode($resultado);
?>